import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#201f1f",
        "inverse-primary": "#a14100",
        "secondary-fixed": "#26e6ff",
        surface: "#0e0e0e",
        "on-tertiary": "#42003a",
        secondary: "#00e3fd",
        "surface-tint": "#ff9159",
        "surface-variant": "#262626",
        "on-primary-fixed": "#000000",
        "error-dim": "#d53d18",
        "secondary-container": "#006875",
        "surface-container-highest": "#262626",
        "inverse-surface": "#fcf9f8",
        "on-secondary-container": "#e8fbff",
        tertiary: "#ff59e3",
        "surface-dim": "#0e0e0e",
        "inverse-on-surface": "#565555",
        "on-tertiary-container": "#1b0017",
        "primary-fixed-dim": "#f66700",
        "secondary-fixed-dim": "#00d7f0",
        "tertiary-dim": "#ff59e3",
        outline: "#767575",
        "secondary-dim": "#00d4ec",
        "on-secondary": "#004d57",
        "on-error-container": "#ffd2c8",
        "tertiary-fixed-dim": "#ff68e3",
        "surface-container-low": "#131313",
        "on-surface-variant": "#adaaaa",
        "error-container": "#b92902",
        "on-primary": "#531e00",
        "on-surface": "#ffffff",
        "primary-fixed": "#ff7a2f",
        "on-secondary-fixed-variant": "#005964",
        "on-primary-container": "#401500",
        "outline-variant": "#484847",
        "on-tertiary-fixed-variant": "#6d0061",
        "surface-container": "#1a1919",
        "on-secondary-fixed": "#003a42",
        "on-error": "#450900",
        "surface-bright": "#2c2c2c",
        "on-primary-fixed-variant": "#4f1c00",
        "on-tertiary-fixed": "#33002d",
        "tertiary-container": "#ff05e5",
        error: "#ff7351",
        "primary-dim": "#ff7524",
        primary: "#ff9159",
        "surface-container-lowest": "#000000",
        "tertiary-fixed": "#ff85e4",
        "primary-container": "#ff7a2f",
        "on-background": "#ffffff",
        background: "#0e0e0e",
        "vibrant-blue": "#1978e5",
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      backgroundImage: {
        "radial-glow": "radial-gradient(var(--tw-gradient-stops))",
      },
      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(1.5rem)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        "fade-left": {
          from: { opacity: "0", transform: "translateX(-1.5rem)" },
          to:   { opacity: "1", transform: "translateX(0)" },
        },
        "fade-right": {
          from: { opacity: "0", transform: "translateX(1.5rem)" },
          to:   { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "fade-up":    "fade-up 0.65s ease-out both",
        "fade-in":    "fade-in 0.5s ease-out both",
        "fade-left":  "fade-left 0.65s ease-out both",
        "fade-right": "fade-right 0.65s ease-out both",
      },
    },
  },
  plugins: [],
};

export default config;
