import { Product } from "./data";


export const products: Product[] = [
  {
    id: 1,
    name: "Channel Runner",
    price: 340,
    series: "Tech-Series // 01",
    image: "/channel-runner.webp",
    imageAlt: "Channel Runner Sneaker",
    rotateOnHover: "cw",
    glowColor: "primary",
    badge: { text: "98% Quality Match", color: "primary" },
  },
  {
    id: 2,
    name: "Asics Gel Kayano 14",
    price: 295,
    series: "Limited // Alpha",
    image: "/asics-gel-kayano.jpg",
    imageAlt: "Asics Gel Kayano 14 White Midnight",
    rotateOnHover: "ccw",
    glowColor: "tertiary",
  },
  {
    id: 3,
    name: "Osiris D3",
    price: 260,
    series: "Performance // V2",
    image: "/osiris-d3.webp",
    imageAlt: "Osiris D3 Blue Grey Sneaker",
    rotateOnHover: "cw",
    glowColor: "secondary",
    badge: { text: "95% Quality Match", color: "secondary" },
  },
  {
    id: 4,
    name: "LV Trainer",
    price: 310,
    series: "Base // Modular",
    image: "/lv-trainer.webp",
    imageAlt: "Louis Vuitton LV Trainer Denim Sneaker",
    rotateOnHover: "ccw",
    glowColor: "primary",
  },
  {
    id: 5,
    name: "Dior B30",
    price: 376,
    series: "Elite // Chronos",
    image: "/dior-b30.avif",
    imageAlt: "Dior B30 Sneaker",
    rotateOnHover: "cw",
    glowColor: "tertiary",
    badge: { text: "99% Quality Match", color: "tertiary" },
  },
  {
    id: 6,
    name: "Nocta Hot Step",
    price: 325,
    series: "Stealth // Dark",
    image: "/nocta-hot-step.webp",
    imageAlt: "Nocta Hot Step Orange Sneaker",
    rotateOnHover: "ccw",
    glowColor: "primary",
  },
  {
    id: 7,
    name: "Yeezy Slides",
    price: 290,
    series: "Thermal // 09",
    image: "/yeezy-slides.webp",
    imageAlt: "Yeezy Slides Sneaker",
    rotateOnHover: "cw",
    glowColor: "primary",
    badge: { text: "92% Quality Match", color: "primary" },
  },
  {
    id: 8,
    name: "Próximamente",
    price: 0,
    series: "Spectrum // Pro",
    image: "",
    imageAlt: "Prism Core Sneaker",
    rotateOnHover: "ccw",
    glowColor: "tertiary",
  },
];
